import { IGroup } from "@/types/group";

const getRandomCoordinate = (base: number, offset: number) => {
  return base + (Math.random() - 0.5) * offset;
};

const GenericGroups: IGroup[] = [
  {
    id: "1",
    name: "Health Enthusiasts",
    description: "A group for people passionate about health and wellness.",
    ownerId: "owner1",
    members: ["member1", "member2", "member3"],
    rating: "4.5",
    location: "City Park",
    geolocationX: getRandomCoordinate(45.7479, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
  {
    id: "2",
    name: "Fitness Freaks",
    description: "A group for fitness enthusiasts to share tips and workouts.",
    ownerId: "owner2",
    members: ["member4", "member5", "member6"],
    rating: "4.7",
    location: "Fitness Center",
    geolocationX: getRandomCoordinate(45.7479, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
  {
    id: "3",
    name: "Yoga Lovers",
    description: "A group for people who love practicing yoga.",
    ownerId: "owner3",
    members: ["member7", "member8", "member9"],
    rating: "4.8",
    location: "Yoga Studio",
    geolocationX: getRandomCoordinate(45.7479, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
  {
    id: "4",
    name: "Nutrition Experts",
    description:
      "A group for sharing knowledge about nutrition and healthy eating.",
    ownerId: "owner4",
    members: ["member10", "member11", "member12"],
    rating: "4.6",
    location: "Community Center",
    geolocationX: getRandomCoordinate(45.7479, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
  {
    id: "5",
    name: "Mental Health Advocates",
    description: "A group for promoting mental health awareness and support.",
    ownerId: "owner5",
    members: ["member13", "member14", "member15"],
    rating: "4.9",
    location: "Mental Health Clinic",
    geolocationX: getRandomCoordinate(45.7479, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
  {
    id: "6",
    name: "Cycling Club",
    description: "A group for cycling enthusiasts to plan rides and events.",
    ownerId: "owner6",
    members: ["member16", "member17", "member18"],
    rating: "4.4",
    location: "Bike Shop",
    geolocationX: getRandomCoordinate(45.7479, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
  {
    id: "7",
    name: "Running Group",
    description: "A group for runners to share routes and training plans.",
    ownerId: "owner7",
    members: ["member19", "member20", "member21"],
    rating: "4.3",
    location: "Running Track",
    geolocationX: getRandomCoordinate(45.7479, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
  {
    id: "8",
    name: "Swimming Squad",
    description: "A group for swimmers to practice and compete together.",
    ownerId: "owner8",
    members: ["member22", "member23", "member24"],
    rating: "4.6",
    location: "Swimming Pool",
    geolocationX: getRandomCoordinate(45.7479, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
  {
    id: "9",
    name: "Hiking Enthusiasts",
    description: "A group for people who love hiking and exploring nature.",
    ownerId: "owner9",
    members: ["member25", "member26", "member27"],
    rating: "4.7",
    location: "Mountain Trail",
    geolocationX: getRandomCoordinate(45.7479, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
  {
    id: "10",
    name: "Dance Crew",
    description: "A group for dancers to practice and perform together.",
    ownerId: "owner10",
    members: ["member28", "member29", "member30"],
    rating: "4.8",
    location: "Dance Studio",
    geolocationX: getRandomCoordinate(45.7479, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
  {
    id: "11",
    name: "Oncology Support Group",
    description: "A group for unity.",
    ownerId: "owner6",
    members: ["member16", "member17", "member18"],
    rating: "4.4",
    location: "Strada Libertatii nr. 6",
    geolocationX: getRandomCoordinate(45.75, 0.02),
    geolocationY: getRandomCoordinate(21.2187, 0.02),
  },
];

export { GenericGroups };
