import { IIllness, ISymptomReport } from "@/types/illness";

const GenericIllnesses: IIllness[] = [
  {
    id: "1",
    name: "Common Cold",
    description: "A viral infection of the upper respiratory tract.",
    date: new Date("2023-11-01T09:00:00Z"),
    pacientId: "1",
    doctorId: "6",
    prescriptionId: "",
    symptomsId: ["201", "202", "203"],
    tags: ["viral", "respiratory", "contagious"],
  },
  {
    id: "2",
    name: "Flu",
    description: "An infectious disease caused by the influenza virus.",
    date: new Date("2023-11-02T10:30:00Z"),
    pacientId: "2",
    doctorId: "7",
    prescriptionId: "",
    symptomsId: ["204", "205", "206"],
    tags: ["viral", "respiratory", "seasonal"],
  },
  {
    id: "3",
    name: "Diabetes",
    description:
      "A chronic condition that affects the way the body processes blood sugar.",
    date: new Date("2023-11-03T11:00:00Z"),
    pacientId: "3",
    doctorId: "8",
    prescriptionId: "",
    symptomsId: ["207", "208", "209"],
    tags: ["chronic", "metabolic", "endocrine"],
  },
  {
    id: "4",
    name: "Hypertension",
    description:
      "A condition in which the force of the blood against the artery walls is too high.",
    date: new Date("2023-11-04T09:30:00Z"),
    pacientId: "4",
    doctorId: "9",
    prescriptionId: "104",
    symptomsId: ["210", "211", "212"],
    tags: ["chronic", "cardiovascular", "lifestyle"],
  },
  {
    id: "5",
    name: "Asthma",
    description:
      "A condition in which your airways narrow and swell and may produce extra mucus.",
    date: new Date("2023-11-05T14:00:00Z"),
    pacientId: "5",
    doctorId: "10",
    prescriptionId: "105",
    symptomsId: ["213", "214", "215"],
    tags: ["chronic", "respiratory", "allergic"],
  },
  {
    id: "6",
    name: "Migraine",
    description:
      "A headache of varying intensity, often accompanied by nausea and sensitivity to light and sound.",
    date: new Date("2023-11-06T15:30:00Z"),
    pacientId: "6",
    doctorId: "6",
    prescriptionId: "106",
    symptomsId: ["216", "217", "218"],
    tags: ["neurological", "chronic", "pain"],
  },
  {
    id: "7",
    name: "Allergic Rhinitis",
    description:
      "An allergic reaction that causes sneezing, congestion, and a runny nose.",
    date: new Date("2023-11-07T09:00:00Z"),
    pacientId: "7",
    doctorId: "7",
    prescriptionId: "107",
    symptomsId: ["219", "220", "221"],
    tags: ["allergic", "respiratory", "seasonal"],
  },
  {
    id: "8",
    name: "Eczema",
    description: "A condition that makes your skin red and itchy.",
    date: new Date("2023-11-08T10:30:00Z"),
    pacientId: "8",
    doctorId: "8",
    prescriptionId: "108",
    symptomsId: ["222", "223", "224"],
    tags: ["chronic", "skin", "allergic"],
  },
  {
    id: "9",
    name: "Arthritis",
    description: "Inflammation of one or more of your joints.",
    date: new Date("2023-11-09T11:00:00Z"),
    pacientId: "9",
    doctorId: "9",
    prescriptionId: "109",
    symptomsId: ["225", "226", "227"],
    tags: ["chronic", "joint", "pain"],
  },
  {
    id: "10",
    name: "Depression",
    description:
      "A mood disorder that causes a persistent feeling of sadness and loss of interest.",
    date: new Date("2023-11-10T09:30:00Z"),
    pacientId: "10",
    doctorId: "10",
    prescriptionId: "110",
    symptomsId: ["228", "229", "230"],
    tags: ["mental", "chronic", "mood"],
  },
];

const GenericSymptomReports: ISymptomReport[] = [
  {
    id: "1",
    symptoms: "Cough, Sore Throat",
    description:
      "Patient has been experiencing a persistent cough and sore throat for the past week.",
    severity: 3,
    emergency: false,
    date: new Date("2023-11-01T09:00:00Z"),
    pacientId: "1",
    doctorId: ["6"],
  },
  {
    id: "2",
    symptoms: "Fever, Body Aches",
    description:
      "Patient reports high fever and body aches for the last three days.",
    severity: 4,
    emergency: false,
    date: new Date("2023-11-02T10:30:00Z"),
    pacientId: "2",
    doctorId: ["7"],
  },
  {
    id: "3",
    symptoms: "High Blood Sugar",
    description:
      "Patient's blood sugar levels have been consistently high despite medication.",
    severity: 5,
    emergency: true,
    date: new Date("2023-11-03T11:00:00Z"),
    pacientId: "3",
    doctorId: ["8"],
  },
  {
    id: "4",
    symptoms: "Headache, Dizziness",
    description:
      "Patient experiences frequent headaches and dizziness, especially in the morning.",
    severity: 2,
    emergency: false,
    date: new Date("2023-11-04T09:30:00Z"),
    pacientId: "4",
    doctorId: ["9"],
  },
  {
    id: "5",
    symptoms: "Shortness of Breath, Wheezing",
    description:
      "Patient has difficulty breathing and wheezing, especially during physical activity.",
    severity: 4,
    emergency: true,
    date: new Date("2023-11-05T14:00:00Z"),
    pacientId: "5",
    doctorId: ["10"],
  },
  {
    id: "6",
    symptoms: "Severe Headache, Nausea",
    description:
      "Patient reports severe headaches accompanied by nausea and sensitivity to light.",
    severity: 5,
    emergency: true,
    date: new Date("2023-11-06T15:30:00Z"),
    pacientId: "6",
    doctorId: ["6"],
  },
  {
    id: "7",
    symptoms: "Sneezing, Runny Nose",
    description:
      "Patient has been sneezing frequently and has a runny nose, likely due to allergies.",
    severity: 2,
    emergency: false,
    date: new Date("2023-11-07T09:00:00Z"),
    pacientId: "7",
    doctorId: ["7"],
  },
  {
    id: "8",
    symptoms: "Itchy Skin, Redness",
    description:
      "Patient's skin is itchy and red, possibly due to eczema flare-up.",
    severity: 3,
    emergency: false,
    date: new Date("2023-11-08T10:30:00Z"),
    pacientId: "8",
    doctorId: ["8"],
  },
  {
    id: "9",
    symptoms: "Joint Pain, Swelling",
    description:
      "Patient experiences joint pain and swelling, particularly in the knees and hands.",
    severity: 4,
    emergency: false,
    date: new Date("2023-11-09T11:00:00Z"),
    pacientId: "9",
    doctorId: ["9"],
  },
  {
    id: "10",
    symptoms: "Persistent Sadness, Loss of Interest",
    description:
      "Patient reports persistent feelings of sadness and loss of interest in daily activities.",
    severity: 4,
    emergency: true,
    date: new Date("2023-11-10T09:30:00Z"),
    pacientId: "10",
    doctorId: ["10"],
  },
];

export { GenericIllnesses, GenericSymptomReports };
