import { IIllness } from "@/types/illness";

const GenericIllnesses: IIllness[] = [
  {
    id: "1",
    name: "Common Cold",
    description: "A viral infection of the upper respiratory tract.",
    date: new Date("2023-11-01T09:00:00Z"),
    pacientId: "1",
    doctorId: "6",
    prescriptionId: "101",
    symptomsId: ["201", "202", "203"],
    tags: ["viral", "respiratory", "contagious"],
  },
  {
    id: "2",
    name: "Flu",
    description: "An infectious disease caused by the influenza virus.",
    date: new Date("2023-11-02T10:30:00Z"),
    pacientId: "2",
    doctorId: "7",
    prescriptionId: "102",
    symptomsId: ["204", "205", "206"],
    tags: ["viral", "respiratory", "seasonal"],
  },
  {
    id: "3",
    name: "Diabetes",
    description:
      "A chronic condition that affects the way the body processes blood sugar.",
    date: new Date("2023-11-03T11:00:00Z"),
    pacientId: "3",
    doctorId: "8",
    prescriptionId: "103",
    symptomsId: ["207", "208", "209"],
    tags: ["chronic", "metabolic", "endocrine"],
  },
  {
    id: "4",
    name: "Hypertension",
    description:
      "A condition in which the force of the blood against the artery walls is too high.",
    date: new Date("2023-11-04T09:30:00Z"),
    pacientId: "4",
    doctorId: "9",
    prescriptionId: "104",
    symptomsId: ["210", "211", "212"],
    tags: ["chronic", "cardiovascular", "lifestyle"],
  },
  {
    id: "5",
    name: "Asthma",
    description:
      "A condition in which your airways narrow and swell and may produce extra mucus.",
    date: new Date("2023-11-05T14:00:00Z"),
    pacientId: "5",
    doctorId: "10",
    prescriptionId: "105",
    symptomsId: ["213", "214", "215"],
    tags: ["chronic", "respiratory", "allergic"],
  },
  {
    id: "6",
    name: "Migraine",
    description:
      "A headache of varying intensity, often accompanied by nausea and sensitivity to light and sound.",
    date: new Date("2023-11-06T15:30:00Z"),
    pacientId: "6",
    doctorId: "6",
    prescriptionId: "106",
    symptomsId: ["216", "217", "218"],
    tags: ["neurological", "chronic", "pain"],
  },
  {
    id: "7",
    name: "Allergic Rhinitis",
    description:
      "An allergic reaction that causes sneezing, congestion, and a runny nose.",
    date: new Date("2023-11-07T09:00:00Z"),
    pacientId: "7",
    doctorId: "7",
    prescriptionId: "107",
    symptomsId: ["219", "220", "221"],
    tags: ["allergic", "respiratory", "seasonal"],
  },
  {
    id: "8",
    name: "Eczema",
    description: "A condition that makes your skin red and itchy.",
    date: new Date("2023-11-08T10:30:00Z"),
    pacientId: "8",
    doctorId: "8",
    prescriptionId: "108",
    symptomsId: ["222", "223", "224"],
    tags: ["chronic", "skin", "allergic"],
  },
  {
    id: "9",
    name: "Arthritis",
    description: "Inflammation of one or more of your joints.",
    date: new Date("2023-11-09T11:00:00Z"),
    pacientId: "9",
    doctorId: "9",
    prescriptionId: "109",
    symptomsId: ["225", "226", "227"],
    tags: ["chronic", "joint", "pain"],
  },
  {
    id: "10",
    name: "Depression",
    description:
      "A mood disorder that causes a persistent feeling of sadness and loss of interest.",
    date: new Date("2023-11-10T09:30:00Z"),
    pacientId: "10",
    doctorId: "10",
    prescriptionId: "110",
    symptomsId: ["228", "229", "230"],
    tags: ["mental", "chronic", "mood"],
  },
];

export { GenericIllnesses };
